version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:.
    ports:
      - "8000:8000"
    depends_on:
      - db
    network_mode: host